<a href="https://colab.research.google.com/github/Sujihari/Python-learning/blob/master/lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# python list Vs Numpy Array

a = [1,2,3,4]
type(a)

list

In [ ]:
res =[i**2 for i in a]
print(res)

[1, 4, 9, 16]


In [ ]:
import numpy as np
arr = np.array(a)
print(arr)

[1 2 3 4]


In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr ** 2


array([ 1,  4,  9, 16])

In [ ]:
a = list(range(100))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
arr = np.arange(100)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr = np.arange(3, 10, 2)
arr

array([3, 5, 7, 9])

In [ ]:
# unique feature in numpy which is not in list (.5)
arr = np.arange(3,10.5)
arr


array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# unique feature in numpy which is not in list (.5)

arr = np.arange(3, 10, 0.5)
arr

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [ ]:
#dimension size and shape of NdArrays

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#shape will give as tuple if it is a single element so (10 ,)
arr.shape

(10,)

In [ ]:
l =[[1,2],[3,5]]
arr2 = np.array(l)
print(arr2)

[[1 2]
 [3 5]]


In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr2.shape

(2, 2)

In [ ]:
#dimensions\
arr2.ndim

2

In [ ]:
#No .of elements
arr2.size

4

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
a = np.array([])
print(a.ndim, a.shape)

1 (0,)


In [ ]:
m = [2,3,4,5,6,7,8,9,10]
m1 = [2,3,4,5,6,7,8,9,10]

In [ ]:
m[6:8] = m1[-1:2:-1]
print(m)
print(m1)

[2, 3, 4, 5, 6, 7, 10, 9, 8, 7, 6, 5, 8, 7, 6, 5, 8, 7, 6, 5, 10]
[2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
What will be the output of a?
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]
print(a)

[1, 2, 6, 7, 8]


In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-1]
print(a)

[1, 2, 3, 6, 7, 8]


In [ ]:
score = np.loadtxt("survey.txt")

FileNotFoundError: survey.txt not found.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
res = np.arange(21, 72, 2)
print(res)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
type(arr)

numpy.ndarray

In [ ]:
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [ ]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])

6


In [ ]:
import numpy as np
a = np.arange(1, 17)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
#If suppose while reshaping the matrix u know only rows and u dont want to put or dont know how many columns to put , jzt if u put -1 it take number by itslef (4 rows I gave we have 16 numbers so 16/4 = 4 , so if u put -1 it will calculate by own)
import numpy as np
a = a.reshape(4,-1)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np
a = a.reshape(8,-1)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
# same for row also we can put -1
import numpy as np
a = a.reshape(-1,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np
a = a.reshape(4, -3)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Transpose matrix
import numpy as np
a = a.T
print(a)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [ ]:
a.T.shape


(4, 4)

In [ ]:
a= a.shape
print(a)

(4, 4)


In [ ]:
import numpy as np
a = a.reshape(2, 8)
print(a)

[[ 1  5  9 13  2  6 10 14]
 [ 3  7 11 15  4  8 12 16]]


In [ ]:
a.shape

(2, 8)

In [ ]:
len(a)

2

In [ ]:
# calculating rows using shape
a.shape[0]

2

In [ ]:
#calculating columns
a.shape[1]

8

In [ ]:
import numpy as np
a = a.reshape(8,2)
print(a)

[[ 1  5]
 [ 9 13]
 [ 2  6]
 [10 14]
 [ 3  7]
 [11 15]
 [ 4  8]
 [12 16]]


In [ ]:
#indexing and Slicing
a[0]


array([1, 5])

In [ ]:
a[-1]

array([12, 16])

In [ ]:
#to get last element
a[-1][-1]

16

In [ ]:
# in 0th index 1st element
a[0][1]

5

In [ ]:
# we can write like this as well
a[0,1]

5

In [ ]:
#slicing
import numpy as np
a = a.reshape(4, 4)
print(a)


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [ ]:
#if I want only 6,10, 14 element
a[1,[1,2,3]]

array([ 6, 10, 14])

In [ ]:
#arrya slicing of row , slicing of column, if I want 6,10,14 and 7, 11,15
a[1:3,1:]

array([[ 6, 10, 14],
       [ 7, 11, 15]])

In [ ]:
# or in another way, -1 means it will give last row but in slicing it will not give last row. (1 to 10) -> (1,2,3,4,5,6,7,8,9)
a[1:-1, 1:4]

array([[ 6, 10, 14],
       [ 7, 11, 15]])

In [ ]:
a[0:3,1:3]

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [ ]:
a[0:3,0:3]

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
#fancy indexing
import numpy as np
a = np.arange(20).reshape(4,-1)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# masking I want the element which is less than 10
a<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
a[a < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
print(a)

[-1  1 -1  3 -1  5]


In [ ]:
# Aggregate function
import numpy as np
mat = np.arange(20).reshape(4,-1)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
mat.sum()

190

In [ ]:
mat.min()

0

In [ ]:
mat.max()

19

In [ ]:
mat.mean()

9.5

In [ ]:
#if we want sum of rows we want to collapse  the colums so colum axis = 1 (sum of rows and columns)
mat.sum(axis = 1)

array([10, 35, 60, 85])

In [ ]:
#if we want sum of columns we want to collapse  the rows so rows axis = 0
mat.sum(axis = 0)

array([30, 34, 38, 42, 46])

In [ ]:
#to get sum of last column
mat.sum(axis = 0)[-1]

46

In [ ]:
# to get min and max in rows and colun
mat.min(axis = 0)

array([0, 1, 2, 3, 4])

In [ ]:
# to get min and max in rows and col
# min in rows
mat.min(axis = 0)[0]

0

In [ ]:
#last row
mat.max(axis = 0)[-1]

19

In [ ]:
mat.max(axis=1)[0]

4

In [ ]:
mat.min(axis=1)[1]

5

In [ ]:
mat.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


# New Section

In [ ]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [ ]:
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56


In [ ]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [ ]:
def reverse_column(arr):
  rev=arr[:,::-1]
  return rev

In [ ]:
arr = [[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]]

In [ ]:
reverse_column(arr)

TypeError: list indices must be integers or slices, not tuple

In [ ]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
#numpy -3
What will the shape of array ?
arr = np.arange(12)
arr = arr.reshape(-1,4)

# it is 3X4

In [ ]:
#sorting in Numpy arrays
import numpy as np
a = np.array([2,1,3,5,4])

In [ ]:
np.sort(a)

array([1, 2, 3, 4, 5])

In [ ]:
#if we print a again it will not give the sorted array..it will give the old array
#np.sort(a)---> gives a copy of sorted array array a

print(a)

[2 1 3 5 4]


In [ ]:
# we cas assign sorted array

b = np.sort(a)
print(b)

[1 2 3 4 5]


In [ ]:
# arr.sort --> sort array in place (without using numpy)

a.sort()
print(a)

[1 2 3 4 5]


In [ ]:
#reverse order
a[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
#sorting 2D array

A = np.array([[4,2,1],[5,7,6],[3,1,2]])


In [ ]:
A

array([[4, 2, 1],
       [5, 7, 6],
       [3, 1, 2]])

In [ ]:
A.shape

(3, 3)

In [ ]:
# data will be sorted according to row wise by default  axis = 1 or -1(column) it disturbs row so it is sorted according to row wise
np.sort(A)

array([[1, 2, 4],
       [5, 6, 7],
       [1, 2, 3]])

In [ ]:
#data will be sorted in  column wise because axis = 0 (row)it should disturb column
np.sort(A , axis=0)

array([[3, 1, 1],
       [4, 2, 2],
       [5, 7, 6]])

In [ ]:
A


array([[4, 2, 1],
       [5, 7, 6],
       [3, 1, 2]])

In [ ]:
# now we want to sort all element like both axis [[1,1,2],[2,3,4],[5,6,7]]
np.sort(A.flatten()).reshape(A.shape)

array([[1, 1, 2],
       [2, 3, 4],
       [5, 6, 7]])

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

def sort_birds(birds, age):
  sorted_age = np.sort(age)
  result = np.array(birds)[sorted_age]
  return result


In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
sort_birds(birds, age)


IndexError: arrays used as indices must be of integer (or boolean) type

In [ ]:
# elements wise operation
a= np.arange(1,6)
a


array([1, 2, 3, 4, 5])

In [ ]:
#it will add 5 to all elements
a+5

array([ 6,  7,  8,  9, 10])

In [ ]:
a*5

array([ 5, 10, 15, 20, 25])

In [ ]:
b = np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [ ]:
# it will add corresponding elements (vector operation)
a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
#using numpy

np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [ ]:
np.add(3,4)

7

In [ ]:
m = np.arange(12).reshape(-1,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
n = np.arange(13,25).reshape(-1,4)
n

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
print(m.shape, n.shape)

(3, 4) (3, 4)


In [ ]:
m+n

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [ ]:
m*n

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [ ]:
# Matrix Multiplication
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape

(2, 2)

In [ ]:
b= np.arange(2,8).reshape(2,3)
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
b.shape

(2, 3)

In [ ]:
# we can multiply if no of columns = no.of rows ( in a 2 columns and in b 2 rows i.e shape for a is (2,2)(r1,c1) and shape of b is (2,3)(r2,c2) so c1 = r2 we do matrix mul using np.dot
np.dot(a , b)



array([[12, 15, 18],
       [26, 33, 40]])

In [ ]:
np.dot(a,3)

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
# in matmul scalar object are not allowed
np.matmul(a,3)
# it throws an error

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])


In [ ]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)


array([3, 7])

In [ ]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A)
print(A[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
# vectorization

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
# we can do element wise
a * 2

array([0, 2, 4, 6, 8])

In [ ]:
# I want to perform element wise calculation using function

def new_ops(a):
  if a%2 == 0:
    return a**2
  else:
    return a**3

In [ ]:
# we can't perform element wise only single value can be given in func,
new_ops(4)

16

In [ ]:
# here if we use vector in func , we can use element wise calculation

cool_ope = np.vectorize(new_ops)

In [ ]:
# now it will perform element wise cal
cool_ope(a)

array([ 0,  1,  4, 27, 16])

In [ ]:
# NUmpy - 4

import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [ ]:
# I am chaning the a value of 0th index
a[0] = 100
a

array([100,   1,   2,   3])

In [ ]:
import numpy as np
a=np.arange(4)
print(f'a: {a}')
c = a+2
print(f'c: {c}')
a[0] = 100
print(f'a: {a}')
print(f'c: {c}')
print(np.shares_memory(a,c)) # checking whether any connection between a and c


a: [0 1 2 3]
c: [2 3 4 5]
a: [100   1   2   3]
c: [2 3 4 5]
False


In [ ]:
import numpy as np
a=np.arange(4)
print(f'a: {a}')
b = a.reshape(2,2)
print(f'b: {b}')
a[0] = 100
print(f'a: {a}')
print(f'b: {b}')
print(np.shares_memory(a,b)) # checking whether any connection between a and b

a: [0 1 2 3]
b: [[0 1]
 [2 3]]
a: [100   1   2   3]
b: [[100   1]
 [  2   3]]
True


In [ ]:
import numpy as np
a=np.arange(10)
print(f'a: {a}')
b = a[::2] # 02468
print(f'b: {b}')
a[0] = 100
print(f'a: {a}')
print(f'b: {b}')
print(np.shares_memory(a,b)) # checking whether any connection between a and b

a: [0 1 2 3 4 5 6 7 8 9]
b: [0 2 4 6 8]
a: [100   1   2   3   4   5   6   7   8   9]
b: [100   2   4   6   8]
True


In [ ]:
# memory usage in numpy:
__> Shallow copy(np.shares_memory == True) : reshaping, slicing
__>Deep copy (np.shares_memory == False) : arithmetic operation, masking

In [ ]:
# View
import numpy as np
a=np.arange(10)
print(f'a: {a}')
b = a.view() # shallow copy
print(f'a:{b}')
print(np.shares_memory(a,b))



a: [0 1 2 3 4 5 6 7 8 9]
a:[0 1 2 3 4 5 6 7 8 9]
True


In [ ]:
#copy
import numpy as np
a=np.arange(10)
print(f'a: {a}')
b = a.copy() # deep copy
print(f'a:{b}')
print(np.shares_memory(a,b))

a: [0 1 2 3 4 5 6 7 8 9]
a:[0 1 2 3 4 5 6 7 8 9]
False


In [ ]:
# using import copy
import copy
a=np.arange(10)
print(f'a: {a}')
b = copy.deepcopy(a) # deep copy
print(f'a:{b}')
print(np.shares_memory(a,b))

a: [0 1 2 3 4 5 6 7 8 9]
a:[0 1 2 3 4 5 6 7 8 9]
False


In [ ]:
a = [0,1,2,3,4,5]
b = a[a%1 == 0]
b[0] = 10
a[:2]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
#splitting

import numpy as np
a = np.arange(9)
print(a)
print(np.split(a,3))


[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
x = np.arange(0,120,10) # starts with 0 ends with 120 means it will give till 110, and jump is 10 (0,10,20,30...110)
print(x)
print(np.split(x,[3,5,6])) # split x into 3rd index , 5th index and 6th index

[  0  10  20  30  40  50  60  70  80  90 100 110]
[array([ 0, 10, 20]), array([30, 40]), array([50]), array([ 60,  70,  80,  90, 100, 110])]


In [ ]:
#horizontal split
c = np .arange(16).reshape(4,4)
print(c)
print(np.hsplit(c,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
c = np .arange(16).reshape(4,4)
print(c)
print(np.hsplit(c,[2])) # spliting with 2nd index

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [ ]:
c = np .arange(24).reshape(6,4)
print(c)
print(np.hsplit(c,[2,3]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]


In [ ]:
# vertical split
c = np .arange(16).reshape(4,4)
print(c)
print('__' *30)
print(np.vsplit(c,4))
print('__' *30)
print(np.vsplit(c,[2])) # using index

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
____________________________________________________________
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
____________________________________________________________
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.vsplit(arr,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [ ]:
#vertical stacking (column should be same)
a = np.arange(1 ,5)
b= np.arange(2,6)
c= np.arange(3,7)
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')
print('----'*35)

np.vstack([a,b,c]) # stacking all together number of columns should be equal

a: [1 2 3 4]
b: [2 3 4 5]
c: [3 4 5 6]
--------------------------------------------------------------------------------------------------------------------------------------------


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [ ]:
a = np.arange(12).reshape(4,3)
b=np.arange(12,21).reshape(3,3) # column size should be same... for a and b
print(a)
print(b)
print('___'*78)
np.vstack([a,b]) # stacking

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
#What will be the output of following code?
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# horizontal stacking(rows should be same)
a = np.arange(12).reshape(3,4)
b=np.arange(12,21).reshape(3,3) # row size should be same... for a and b
print(a)
print(b)
print('___'*78)
np.hstack([a,b])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


array([[ 0,  1,  2,  3, 12, 13, 14],
       [ 4,  5,  6,  7, 15, 16, 17],
       [ 8,  9, 10, 11, 18, 19, 20]])

In [ ]:
# what will be the output of this?
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a, b))

Object `this` not found.


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#concatenate
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
print(np.concatenate((a,b))) # by default it is axis = 0 vstack
print('__'*34)
print(np.concatenate((a, b),axis=1)) # it is axis = 1 hstack

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
____________________________________________________________________
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
arr = np.arange(16).reshape(4,4)
print(np.split(arr,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
arr = np.array([1,2,3,0,-2,4])
arr1 = arr.reshape(2,3)
print(arr1)
print(np.shares_memory(arr,arr1))

[[ 1  2  3]
 [ 0 -2  4]]
True


In [ ]:
a=np.arange(2,3,3)
a

array([2])

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
np.hstack((arr, arr[:, [0]])).shape= (4, 3)

In [ ]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]