<a href="https://colab.research.google.com/github/Sujihari/Python-learning/blob/master/SujithaKumar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
def master_numpy(M2):
  M1=[]
  M3=[]
  for elements in M2:
    if elements > 42:
      M1.append('True')
      M3.extend([elements])

    else:
      M1.append('False')
  return M1,M3

In [2]:
M2 = np.array([35,65,65,22])
print(master_numpy(M2))

(['False', 'True', 'True', 'False'], [65, 65])


In [ ]:
import numpy as np
def integers(a,b,c):
  if a!= b*c:
    return -1
  else:
    return np.ones((b,c))*a

In [ ]:
integers(6,2,3)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [ ]:
import numpy as np
def formula(x,y,p):
  return (np.sum(np.abs(x-y)**p))**(1/p)

In [ ]:
formula(2,5,6)

3.0

In [ ]:
import numpy as np
def formu(m,c,v):
  res = np.arange(m).reshape(c,v)
  res[0,:]
  print(res)



In [ ]:
formu(10,2,5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
formu(10,2,5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
import numpy as np
def array(arr1,arr2):
  return (arr1*arr2)[-1,:]/np.sum(arr1*arr2)[-1,:]

IndexError: invalid index to scalar variable.

In [ ]:
import numpy as np
def boolean(m):
  s1=[]
  for elements in m:
    print(elements)
    if elements==5:
      s1.append('True')
    else:
      s1.append('False')
  return s1

In [ ]:
boolean(np.array([1,2,5,4,5]))

1
2
5
4
5


['False', 'False', 'True', 'False', 'True']

In [ ]:
m= np.array([1,2,5,4,5])
print(m==5)

[False False  True False  True]


In [ ]:
#formatting string

name = "suji"
place = "UK"
print("My name is {} and I live in {}".format(name,place))

My name is suji and I live in UK


In [ ]:
#lastest version of formatting string

name = "suji"
place = "UK"
print(f"My name is {name} and I live in {place}.")

My name is suji and I live in UK.


In [ ]:
# Given a string as input to find the count of upper case char
name = "SUjitHA"

count=0
for i in name:
  if ord(i)>=65 and ord(i)<=90:
    count+=1
print(count)

4


In [ ]:
# Given a string as input to find the upper case char
name = "SUjitHA"

for i in name:
  if ord(i)>=65 and ord(i)<=90:
    print(i, ord(i))

S 83
U 85
H 72
A 65


In [ ]:
#converting my upper case into lower case chr

for i in name:
  if ord(i)>=65 and ord(i)<=90:
    lw_asc = ord(i)+32
    print(chr(lw_asc),i)

s S
u U
h H
a A


In [ ]:
#converting my upper case into lower case chr and print the full name
def upper_to_lower(s):
  ans = ""
  for i in s:
    if ord(i)>=65 and ord(i)<=90:
      lw_asc = ord(i)+32
      ans += chr(lw_asc)
    else:
      ans += i
  print(ans)

In [ ]:
upper_to_lower('LIaaaYa')

liaaaya


In [ ]:
#converting my upper case into lower case chr and lower to upper case
def upper_to_lower_case(s):
  ans = ""
  for i in s:
    if ord(i)>=65 and ord(i)<=90:
      lw_asc = ord(i)+32
      ans += chr(lw_asc)
    elif ord(i)>=97 and ord(i)<=122:
      up_asc = ord(i)-32
      ans += chr(up_asc)
  print(ans)

In [ ]:
upper_to_lower_case('sUJItha')

SujiTHA


In [ ]:
upper_to_lower_case('HaRI KrisHNAN')

hArikRIShnan


In [ ]:
# Dictionary
dict = {"A":20,"B":30, "C":40}
print(dict)

{'A': 20, 'B': 30, 'C': 40}


In [ ]:
dict1 = ["A", "B", "C"]
dict2 = [20, 30, 40]
dict3 = list(zip(dict1, dict2))

print(dict3)

[('A', 20), ('B', 30), ('C', 40)]


In [ ]:
#there will be one key value pair for each unique cher, key will be chr name and value will be count of char

def count(string):

  dict = {}
  for i in string:
    if i in dict:
      dict[i] += 1
    else:
      dict[i] = 1
  return dict

In [ ]:
count("SUJITHAJAAS")

{'S': 2, 'U': 1, 'J': 2, 'I': 1, 'T': 1, 'H': 1, 'A': 3}

In [ ]:
#What will be the output of the following Python code?

dict1 = {'age': 35, 'name': 'abc', 'salary': 45000}

val = dict1['age']

if val in dict1:
    print('This is a member of the dictionary')
else:
    print('This is not a member of the dictionary')

This is not a member of the dictionary


In [ ]:
bbt = {'Sheldon': 1, 'Leonard': 2}
bbt.update({'Penny': 2})
print(bbt)

{'Sheldon': 1, 'Leonard': 2, 'Penny': 2}


In [ ]:
str1 = "quick brown fox word!"
print(str1[12:15], str1[:5], str1[-5:-1], str1[8:110], str1[-4:])

fox quick word own fox word! ord!


In [ ]:
s = "MyPOBoxnumberis310"
print(s.isalnum())

True


In [ ]:
name_lst = ["Vijay", "Vickey"]
tup = ("Item_1", 0.5, name_lst)
name_lst.append("Vishal")
print(tup)

('Item_1', 0.5, ['Vijay', 'Vickey', 'Vishal'])


In [ ]:
fruits = ("Orange")
type(fruits)

str

In [ ]:
set1 = {1, 2, 4}
set2 = {4, 5, 6}
print(len(set1 + set2))

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [ ]:
real_madrid = {
    'name': 'Benzema',
    'age': 35,
    'salary': 8000000,
    'position': 'striker'
}

keys = ['name', 'salary']
sample_dict = real_madrid['name'],real_madrid['salary']

print(sample_dict)

('Benzema', 8000000)


In [ ]:
#Suppose you’re a Data Scientist at a famous football club Real Madrid. There is an individual defined dictionary for all the players at the club and one such is shown below.
#The coach has asked you to give the report of Benzema but with only those items that have keys that are not present in the keys list, for which you defined another dictionary named ‘sample_dict’. Which option can be used to complete the above code snippet to give the report in the form of a dictionary?
#{k : real_madrid[k] for k in real_madrid.keys() if k not in keys}
real_madrid = {
    'name': 'Benzema',
    'age': 35,
    'salary': 8000000,
    'position': 'striker'
}

keys = ['name', 'salary']
sample_dict = {k : real_madrid[k] for k in real_madrid.keys() if k not in keys}
print(sample_dict)

{'age': 35, 'position': 'striker'}


In [ ]:
dictionary= {"scaler": [5, 7, 5, 4, 5], "is": [6, 7, 4, 3, 3], "best": [9, 9, 6, 5, 5]}
max_val = 0
for i in dictionary:
  max_list1=len(set(dictionary[i]))
  if max_list1>max_val:
            max_val=max_list1
            max_key=i
print(max_key)

is


In [ ]:
#merging two dict
dict1 = {'ten': 10, 'twenty':20, 'thirty': 30}
dict2 = {'thirty': 30, 'fifty': 50, 'sixty': 60}

dict3 = dict1.copy()
dict3.update(dict2)
print(dict3)

{'ten': 10, 'twenty': 20, 'thirty': 30, 'fifty': 50, 'sixty': 60}


In [ ]:
os = {'ios': 35, 'android': 30}
os.remove('android')
print(os)

AttributeError: 'dict' object has no attribute 'remove'

In [ ]:
def even_odd(tup):
    Odd = tup[::2]
    Even = tup[1::2]
    print(f"Odd: {tuple(Odd)}")
    print(f"Even: {tuple(Even)}")

In [ ]:
even_odd(10,5,6,7,8,8)

TypeError: even_odd() takes 1 positional argument but 6 were given

In [ ]:
sent1 = "in data analysis we use data and process it further to create better interpreted data"
sent2 = "more and more data will be passively collected"


sent1 = sent1.split()
sent2 = sent2.split()

un_w1 = set(sent1)
un_w2 = set(sent2)
count = len(un_w1)+len(un_w2)
print(count)

20


In [ ]:
sets = {3, 4, 5}
sets = sets.union({1, 2, 3})
print(sets)

{1, 2, 3, 4, 5}


In [ ]:
a={'Aurn', 'Nikhil', 'Seeta'}
a[0]= 'Arun'
print(a)

TypeError: 'set' object does not support item assignment

In [ ]:
tup = (1150 , 'sea','990')
tup[0]= 50
print(tup)

TypeError: 'tuple' object does not support item assignment

In [ ]:
str1 = "Hello"
print(str1*2)

HelloHello


In [ ]:
ord("a")

TypeError: 'str' object is not callable

In [ ]:
print(“hello”+1+2+3)


SyntaxError: invalid character '“' (U+201C) (<ipython-input-23-ced5a2fde0a0>, line 1)

In [ ]:
a = 'hello'
b = a
a = 'yello'

print(b)
print(a)

hello
yello


In [ ]:
ord("z")

122

In [ ]:
name = "SUJITHA"
for i in name:
  if i.isupper():
    print(True)
  else:
    print(False)

True
True
True
True
True
True
True


In [ ]:
ord('H')

72

In [ ]:
s1 = "Sujitha"
s2 = "Su"
if s2 in s1:
    print(s1)
else:
    print("no")

Sujitha


In [ ]:
def string(s2, s1):
  if s2 in s1:
    return True
  else:
    return False

In [ ]:
string("Su","Sujitha")

True

In [ ]:
s1 = "Sujitha Hari"
ans = ""
for i in s1.split():
  ans+=i
print(ans*3)


SujithaHariSujithaHariSujithaHari


In [ ]:
# count the number in string

def digit(s):
  count = 0
  for i in s:
    if i.isdigit():
      count+=1
  return count


In [ ]:
digit('SU2605tha')

4

In [ ]:
A = "scaler"
def find(A):
  return len(A)

In [ ]:
find('scaler')

6

In [ ]:
A = 'aabbcc'
B = 98
def solve(self, A, B):
  for i in A:
    if B == ord(i):
      ans = A.index(i)
    else:
      ans = -1
  return ans

In [ ]:
ord("S")

TypeError: 'str' object is not callable

In [ ]:
ord = "Scaler Academy"
n = len(word)
word1 = word.upper()
word2 = word.lower()

converted_word = ""

for i in range(n):
     if i % 2 == 0:
          converted_word += word2[i]
     else:
          converted_word += word1[i]
print(converted_word)


NameError: name 'word' is not defined

In [ ]:
A = 'aabbcc'
B = 98
result = solve(A, B)
print(result)

TypeError: solve() missing 1 required positional argument: 'B'

In [ ]:
runs = [12,3,44,56,78,90,76]
for i in range(-1, - len(runs) -1, -1):
  print(runs[i])

76
90
78
56
44
3
12


In [ ]:
x = [1, 2]
y = [2, 3]

for i in x:
    for j in y:
        print(i,j, end= " ")

1 2 1 3 2 2 2 3 

In [ ]:
str = " India"
for i in str:
  print(i)

 
I
n
d
i
a


In [ ]:
print(str[1], str[5])

I a


In [ ]:
(i)

In [ ]:
A = input()
for  i in A:
  print(ord(i))

suji
115
117
106
105


In [ ]:
print(str[::-1])

aidnI 


In [ ]:
chr(-98)

ValueError: ignored

In [ ]:
a = 3.141592
print(f'Two decimals:{a:.3f}')

Two decimals:3.142


In [ ]:
 a= 3.141592
 print('Two: {:.2f}, Three: {:.3f}, four: {:.4f}'.format(a, a, a))

Two: 3.14, Three: 3.142, four: 3.1416


In [ ]:
Name = "sujitha"
Age = 30
hername = Name
herage = Age
print('{0} is {1} years old'.format(hername,herage))

sujitha is 30 years old


In [ ]:
class point:
  x= 10.0
  y = 98.0
apoint=point()
print(apoint.x)




10.0


In [ ]:
class point:
   def get_distance(p1, p2):
    return ((p1.x - p2.x)**2 + (p1.y - p2.y)**2)**0.5
    point1 = Point()
    point1.x=10.0
    point1.y=15.0
    point2 = Point()
    point2.x=55.0
    point2.y=30.0




In [ ]:
class Eludi:
  def __init__(self, p1, p2):
    self.point1 = p1
    self.point2 = p2
  def calculate(self):
    x1,y1 = self.point1
    x2,y2 = self.point2

    distance=  ((x2-x1)**2 + (y2 - y1)**2)**0.5

    return distance



In [ ]:
class rectangle:
  def __init__(self,h, w):
    self.height = h
    self.width = w
  def calculate(self):
    x1, y1 = self.height
    x2, y2 = self.width

    X_center = x1+x2 /2.0
    y_center = y1+y2 / 2.0

    return (X_center, y_center)

In [ ]:
height_size = (1,4)
width_size = (5,6)
answer = rectangle(height_size,width_size)
center_point = answer.calculate()
print(center_point)

(3.5, 7.0)


In [ ]:
point_a = (4, 5)
point_b = (7 ,8)
answer = Eludi(point_a,point_b)
distance = answer.calculate()

print(distance)



4.242640687119285


In [ ]:
 get_distance(point1, point2)

NameError: ignored

In [ ]:
a=3.141592
b=3
print('pi:{myvar:.{decimal}f}'.format(myvar=a,decimal=b))

pi:3.142


In [ ]:
a=22.34646
print(f'two deci:{a:.2f}')

two deci:22.35


In [ ]:
c = 45.23158
print(f'td:{c:.2f}')

td:45.23


In [ ]:
c= 45.2315896
print('two:{:.2f},Three:{:.3f}'.format(c, c))

two:45.23,Three:45.232


In [ ]:
a= 3.125478
d = 3
print('pi:{myvar:.{decimal}f}'.format(myvar=a,decimal=d))

pi:3.125


In [ ]:
print('pi:{myvar:.{decimal}f}'.format(myvar=a,decimal=d))

pi:3.125


In [ ]:
def function():
  name = []*5
  age= [0]*5
  height = [0]*5
  for i in range(5):
    name[i]=input('enter the name')
    age[i]=int(input('Enter age'))
    height[i]=float(input('enter the height'))
  for i in range(5):
    print('Name:{0}, Age={1}, height={2:.2f}'.format(name[i],age[i],height[i]))

In [ ]:
def afunction():
 Name = [''] * 5
 Age = [0] * 5
 Height = [0] * 5
 for i in range(5):
  Name[i] = input('Enter name ')
  Age[i] = int(input('Enter age'))
  Height[i] = float(input('Enter height '))
 for i in range(5):
  print('Name: {0}, Age: {1}, Height {2:.2f}'.format(Name[i], Age[i], Height[i]))

In [ ]:
def function(n,m):
  for i in range(n,m,-1):
    if i % 2 == 0:
      print(i)

In [ ]:
def afunction(astr):
  ans = astr.split()
  x= ans[0][::-1]
  return x

In [ ]:
def even_idx(l1):
  n = len(l1)
  if i % 2 == 0:
    del l1[-1]
  else:
    del l1[-2]
  return l1

In [ ]:
even_idx([1,2,3,4,2])

[1, 2, 3, 4]

In [ ]:
#mylist = [1,2,3,4,4,5,5,"fsg",5,67,"gfg"]
for i in range(len(mylist)):
  if i % 2 == 0:
    del mylist[i]
  return mylist

SyntaxError: ignored

In [ ]:
afunction("hello world")

'olleh'

In [ ]:
function(10 ,0)

10
8
6
4
2


In [ ]:
afunction()


TypeError: ignored

In [ ]:
def afunction(str):
  return str[str.find(' ')-1::-1]


In [ ]:
n = int(input())
count = 0
for i in range(n):
  i=n%10
  if i == 1:
    count+=1
print(count)


Streaming output truncated to the last 5000 lines.
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [ ]:
a= [1,3,4]
b=[5,6,7]
c=[8,5,6]

score=[a,b,c]


In [ ]:
print(score)

[[1, 3, 4], [5, 6, 7], [8, 5, 6]]


In [ ]:
total = 0
for i in range(len(score[i])):
  for j in range(len(score[j])):
    total+=score[i][j]
print(total)

IndexError: ignored

In [ ]:
x = 1
for i in range(x):
    x=x+1
    print(i, end= " ")


0 

In [ ]:
i=0
while i<=5:
     if i%2:
        pass
     else:
        print(i, end=" ")
     i+=1

0 2 4 

In [ ]:
if x > 5:
    x = x*3
if x > 15:
    x = 0
print(x)

2


In [ ]:
num = 1
while num > 1:
    num = num // 3
print(num)

1


In [ ]:
afunction("suji smile")

'ijus'

In [ ]:
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]

In [ ]:
def solve(self, A,B):
  return A@B

In [ ]:
print(solve(A,B))

TypeError: ignored